"""empty message

Revision ID: 14de443ddc31
Revises: 2855fec8d81b
Create Date: 2021-04-27 09:58:38.405914

"""
from alembic import op
import sqlalchemy as sa
from app.auth.models import User, db
from app.promo.models import Outlet

# revision identifiers, used by Alembic.
revision = '14de443ddc31'
down_revision = '2855fec8d81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlet_group_advertise',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('outlet_id', sa.Integer(), nullable=True),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['group_advertise.id'], ),
                    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('outlet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'outlet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
    user = User.query.first()
    outlets = Outlet.query
    for outlet in outlets:
        outlet.user_id = user.id
    db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outlet', type_='foreignkey')
    op.drop_column('outlet', 'user_id')
    op.drop_table('outlet_group_advertise')
    # ### end Alembic commands ###
