"""empty message

Revision ID: 1aac71002a28
Revises: 8144b6f56a40
Create Date: 2021-04-06 16:48:10.720190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aac71002a28'
down_revision = '8144b6f56a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_advertise_viewed_date_viewed'), 'advertise_viewed', ['date_viewed'], unique=False)
    op.drop_column('advertise_viewed', 'count')
    op.drop_column('advertise_viewed', 'time_created')
    op.drop_column('advertise_viewed', 'time_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertise_viewed', sa.Column('time_updated', mysql.DATETIME(), nullable=True))
    op.add_column('advertise_viewed', sa.Column('time_created', mysql.DATETIME(), nullable=False))
    op.add_column('advertise_viewed', sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_advertise_viewed_date_viewed'), table_name='advertise_viewed')
    # ### end Alembic commands ###
