"""empty message

Revision ID: 2855fec8d81b
Revises: 6d7724b0f543
Create Date: 2021-04-26 18:00:20.946154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2855fec8d81b'
down_revision = '6d7724b0f543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('ts_create', sa.TIMESTAMP(), nullable=True),
    sa.Column('ts_update', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('date_begin', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('max_count_per_outlet', sa.Integer(), nullable=True),
    sa.Column('bar_code', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlet_mac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=True),
    sa.Column('mac', sa.String(length=32), nullable=True),
    sa.Column('ts_first_seen', sa.TIMESTAMP(), nullable=False),
    sa.Column('ts_last_seen', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlet_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('outlet_ip', sa.String(length=50), nullable=True),
    sa.Column('ts_create', sa.TIMESTAMP(), nullable=False),
    sa.Column('ts_usage', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlet_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('outlet_request_id', sa.Integer(), nullable=True),
    sa.Column('ts_create', sa.TIMESTAMP(), nullable=False),
    sa.Column('ts_usage', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_request_id'], ['outlet_request.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outlet_product')
    op.drop_table('outlet_request')
    op.drop_table('outlet_mac')
    op.drop_table('products')
    op.drop_table('outlet')
    # ### end Alembic commands ###
