"""empty message

Revision ID: 3ccd629f4b36
Revises: 51b537ecff89
Create Date: 2021-04-28 11:18:35.753060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ccd629f4b36'
down_revision = '51b537ecff89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('outlet_group_advertise_ibfk_1', 'outlet_group_advertise', type_='foreignkey')
    op.drop_constraint('outlet_group_advertise_ibfk_2', 'outlet_group_advertise', type_='foreignkey')
    op.create_foreign_key(None, 'outlet_group_advertise', 'group_advertise', ['group_id'], ['id'])
    op.create_foreign_key(None, 'outlet_group_advertise', 'outlet', ['outlet_id'], ['id'])
    op.drop_column('outlet_group_advertise', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outlet_group_advertise', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'outlet_group_advertise', type_='foreignkey')
    op.drop_constraint(None, 'outlet_group_advertise', type_='foreignkey')
    op.create_foreign_key('outlet_group_advertise_ibfk_2', 'outlet_group_advertise', 'group_advertise', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('outlet_group_advertise_ibfk_1', 'outlet_group_advertise', 'outlet', ['outlet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
