"""empty message

Revision ID: 4cc4fea202f7
Revises: 
Create Date: 2021-03-30 15:03:24.734626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc4fea202f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('time_created', sa.DATETIME(), nullable=False),
    sa.Column('time_updated', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('group_advertise',
    sa.Column('time_created', sa.DATETIME(), nullable=False),
    sa.Column('time_updated', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertise',
    sa.Column('time_created', sa.DATETIME(), nullable=False),
    sa.Column('time_updated', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('time_start', sa.DATETIME(), nullable=False),
    sa.Column('time_end', sa.DATETIME(), nullable=True),
    sa.Column('time_delete', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_advertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertise_viewed',
    sa.Column('time_created', sa.DATETIME(), nullable=False),
    sa.Column('time_updated', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('advertise_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date_viewed', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['advertise_id'], ['advertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertise_viewed')
    op.drop_table('advertise')
    op.drop_table('group_advertise')
    op.drop_table('user')
    # ### end Alembic commands ###
