"""empty message

Revision ID: 51b537ecff89
Revises: afa93f012e45
Create Date: 2021-04-28 10:51:03.906743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b537ecff89'
down_revision = 'afa93f012e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlet_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('time_created', sa.DATETIME(), nullable=False),
    sa.Column('time_end', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outlet_sessions')
    # ### end Alembic commands ###
