"""empty message

Revision ID: 5c16cd0f4f7e
Revises: d34f0cf578c8
Create Date: 2021-04-20 21:36:19.997892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c16cd0f4f7e'
down_revision = 'd34f0cf578c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    # ### end Alembic commands ###
