"""empty message

Revision ID: 6d7724b0f543
Revises: 5c16cd0f4f7e
Create Date: 2021-04-22 11:08:00.074505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7724b0f543'
down_revision = '5c16cd0f4f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertise', sa.Column('shows_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertise', 'shows_max')
    # ### end Alembic commands ###
