"""empty message

Revision ID: 810944322f8e
Revises: c582fe4cdb83
Create Date: 2021-04-02 17:08:49.021339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '810944322f8e'
down_revision = 'c582fe4cdb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertise', 'filename',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.create_unique_constraint(None, 'advertise', ['path'])
    op.add_column('group_advertise', sa.Column('status', sa.Enum('disabled', 'enabled', name='statustype'), nullable=False))
    op.add_column('group_advertise', sa.Column('token', sa.String(length=200), nullable=True))
    op.add_column('group_advertise', sa.Column('who_update', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group_advertise', 'user', ['who_update'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_advertise', type_='foreignkey')
    op.drop_column('group_advertise', 'who_update')
    op.drop_column('group_advertise', 'token')
    op.drop_column('group_advertise', 'status')
    op.drop_constraint(None, 'advertise', type_='unique')
    op.alter_column('advertise', 'filename',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
