"""empty message

Revision ID: 8144b6f56a40
Revises: 810944322f8e
Create Date: 2021-04-06 15:35:03.882910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8144b6f56a40'
down_revision = '810944322f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_advertise', 'token',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.create_unique_constraint(None, 'group_advertise', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_advertise', type_='unique')
    op.alter_column('group_advertise', 'token',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
