"""empty message

Revision ID: 84dd7c944418
Revises: e8bc1fdebf0c
Create Date: 2021-04-12 15:17:57.086135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84dd7c944418'
down_revision = 'e8bc1fdebf0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('personal_token', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'personal_token')
    # ### end Alembic commands ###
