"""empty message

Revision ID: ae6f3671dfa9
Revises: 14de443ddc31
Create Date: 2021-04-27 10:17:30.541157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6f3671dfa9'
down_revision = '14de443ddc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('outlet_group_advertise_ibfk_1', 'outlet_group_advertise', type_='foreignkey')
    op.drop_constraint('outlet_group_advertise_ibfk_2', 'outlet_group_advertise', type_='foreignkey')
    op.create_foreign_key(None, 'outlet_group_advertise', 'outlet', ['outlet_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'outlet_group_advertise', 'group_advertise', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outlet_group_advertise', type_='foreignkey')
    op.drop_constraint(None, 'outlet_group_advertise', type_='foreignkey')
    op.create_foreign_key('outlet_group_advertise_ibfk_2', 'outlet_group_advertise', 'outlet', ['outlet_id'], ['id'])
    op.create_foreign_key('outlet_group_advertise_ibfk_1', 'outlet_group_advertise', 'group_advertise', ['group_id'], ['id'])
    # ### end Alembic commands ###
