"""empty message

Revision ID: afa93f012e45
Revises: b9a8bfaaefb6
Create Date: 2021-04-27 18:49:46.035413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa93f012e45'
down_revision = 'b9a8bfaaefb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlet_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=200), nullable=True),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DATETIME(), nullable=False),
    sa.Column('time_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outlet_token')
    # ### end Alembic commands ###
