"""empty message

Revision ID: b48ec3d31993
Revises: 51723a7317e7
Create Date: 2021-04-07 13:36:00.620304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48ec3d31993'
down_revision = '51723a7317e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'user_id')
    # ### end Alembic commands ###
