"""empty message

Revision ID: b9a8bfaaefb6
Revises: ae6f3671dfa9
Create Date: 2021-04-27 10:35:19.831858

"""
from alembic import op
import sqlalchemy as sa
from app.promo.models import Product
from app.auth.models import User, db

# revision identifiers, used by Alembic.
revision = 'b9a8bfaaefb6'
down_revision = 'ae6f3671dfa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    user = User.query.first()
    products = Product.query.all()
    for product in products:
        product.user_id = user.id

    db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###
