"""empty message

Revision ID: c582fe4cdb83
Revises: 4111ce7ee31e
Create Date: 2021-04-01 13:14:14.815060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c582fe4cdb83'
down_revision = '4111ce7ee31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertise', sa.Column('file_extension', sa.String(length=20), nullable=True))
    op.add_column('advertise', sa.Column('filename', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'advertise', ['filename'])
    op.drop_column('advertise', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertise', sa.Column('name', mysql.VARCHAR(length=200), nullable=True))
    op.drop_constraint(None, 'advertise', type_='unique')
    op.drop_column('advertise', 'filename')
    op.drop_column('advertise', 'file_extension')
    # ### end Alembic commands ###
