"""empty message

Revision ID: e8bc1fdebf0c
Revises: 8cb85bb60b10
Create Date: 2021-04-09 09:55:24.217825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bc1fdebf0c'
down_revision = '8cb85bb60b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertise', sa.Column('shows_per_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertise', 'shows_per_day')
    # ### end Alembic commands ###
