"""empty message

Revision ID: ec06e4ace041
Revises: 4cc4fea202f7
Create Date: 2021-03-30 18:55:36.499534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec06e4ace041'
down_revision = '4cc4fea202f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_advertise', sa.Column('time_delete', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_advertise', 'time_delete')
    # ### end Alembic commands ###
